from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import secrets
from http import HTTPStatus
from http.cookies import SimpleCookie
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


ROOT = Path(__file__).resolve().parent
DATABASE_URL = os.environ.get("DATABASE_URL", "")
SESSION_COOKIE = "budget_session"
PBKDF2_ROUNDS = 200_000
ALLOWED_ORIGINS = {
    origin.strip().rstrip("/")
    for origin in os.environ.get("CORS_ORIGINS", "http://127.0.0.1:8000,http://localhost:8000").split(",")
    if origin.strip()
}
COOKIE_SECURE = os.environ.get("COOKIE_SECURE", "").lower() in {"1", "true", "yes"} or bool(os.environ.get("RENDER"))
COOKIE_SAMESITE = os.environ.get("COOKIE_SAMESITE", "None" if COOKIE_SECURE else "Lax")


def connect() -> psycopg.Connection:
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is required. Set it to your Render Postgres Internal Database URL.")
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def init_db() -> None:
    with connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
              id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
              email TEXT NOT NULL UNIQUE,
              password_hash TEXT NOT NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sessions (
              token TEXT PRIMARY KEY,
              user_id INTEGER NOT NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            );
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS user_data (
              user_id INTEGER PRIMARY KEY,
              data JSONB NOT NULL,
              updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            );
            """
        )
        conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_idx ON users (LOWER(email))")


def hash_password(password: str) -> str:
    salt = os.urandom(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, PBKDF2_ROUNDS)
    return f"{PBKDF2_ROUNDS}${base64.b64encode(salt).decode()}${base64.b64encode(digest).decode()}"


def verify_password(password: str, stored_hash: str) -> bool:
    try:
        rounds_text, salt_text, digest_text = stored_hash.split("$", 2)
        rounds = int(rounds_text)
        salt = base64.b64decode(salt_text)
        expected = base64.b64decode(digest_text)
    except (ValueError, TypeError):
        return False

    actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, rounds)
    return hmac.compare_digest(actual, expected)


class BudgetHandler(SimpleHTTPRequestHandler):
    extensions_map = {
        **SimpleHTTPRequestHandler.extensions_map,
        ".js": "application/javascript",
        ".css": "text/css",
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/api/health":
            self.send_json({"ok": True})
            return
        if parsed.path == "/api/me":
            self.handle_me()
            return
        if parsed.path == "/api/data":
            self.handle_get_data()
            return
        super().do_GET()

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/api/signup":
            self.handle_signup()
            return
        if parsed.path == "/api/login":
            self.handle_login()
            return
        if parsed.path == "/api/logout":
            self.handle_logout()
            return
        self.send_json({"error": "Not found"}, HTTPStatus.NOT_FOUND)

    def do_PUT(self) -> None:
        if urlparse(self.path).path == "/api/data":
            self.handle_put_data()
            return
        self.send_json({"error": "Not found"}, HTTPStatus.NOT_FOUND)

    def do_OPTIONS(self) -> None:
        self.send_response(HTTPStatus.NO_CONTENT)
        self.send_cors_headers()
        self.send_header("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Access-Control-Max-Age", "86400")
        self.end_headers()

    def read_json(self) -> dict:
        length = int(self.headers.get("content-length", "0"))
        raw = self.rfile.read(length)
        if not raw:
            return {}
        return json.loads(raw.decode("utf-8"))

    def send_json(self, payload: dict, status: HTTPStatus = HTTPStatus.OK, cookie: str | None = None) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_cors_headers()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("X-Content-Type-Options", "nosniff")
        if cookie:
            self.send_header("Set-Cookie", cookie)
        self.end_headers()
        self.wfile.write(body)

    def send_cors_headers(self) -> None:
        origin = self.headers.get("Origin", "").rstrip("/")
        if origin in ALLOWED_ORIGINS:
            self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Access-Control-Allow-Credentials", "true")
            self.send_header("Vary", "Origin")

    def current_user(self) -> dict | None:
        cookie_header = self.headers.get("Cookie", "")
        cookies = SimpleCookie(cookie_header)
        token_cookie = cookies.get(SESSION_COOKIE)
        if not token_cookie:
            return None

        with connect() as conn:
            return conn.execute(
                """
                SELECT users.id, users.email
                FROM sessions
                JOIN users ON users.id = sessions.user_id
                WHERE sessions.token = %s
                """,
                (token_cookie.value,),
            ).fetchone()

    def create_session(self, user_id: int) -> str:
        token = secrets.token_urlsafe(32)
        with connect() as conn:
            conn.execute("INSERT INTO sessions (token, user_id) VALUES (%s, %s)", (token, user_id))
        secure = "; Secure" if COOKIE_SECURE else ""
        return f"{SESSION_COOKIE}={token}; HttpOnly; SameSite={COOKIE_SAMESITE}; Path=/{secure}"

    def handle_me(self) -> None:
        user = self.current_user()
        if not user:
            self.send_json({"user": None}, HTTPStatus.UNAUTHORIZED)
            return
        self.send_json({"user": {"id": user["id"], "email": user["email"]}})

    def handle_signup(self) -> None:
        try:
            payload = self.read_json()
        except json.JSONDecodeError:
            self.send_json({"error": "Invalid JSON"}, HTTPStatus.BAD_REQUEST)
            return

        email = str(payload.get("email", "")).strip().lower()
        password = str(payload.get("password", ""))
        if "@" not in email or len(password) < 8:
            self.send_json({"error": "Use a valid email and at least 8 password characters."}, HTTPStatus.BAD_REQUEST)
            return

        try:
            with connect() as conn:
                user = conn.execute(
                    "INSERT INTO users (email, password_hash) VALUES (%s, %s) RETURNING id",
                    (email, hash_password(password)),
                ).fetchone()
                user_id = user["id"]
        except psycopg.IntegrityError:
            self.send_json({"error": "That email already has an account."}, HTTPStatus.CONFLICT)
            return

        cookie = self.create_session(user_id)
        self.send_json({"user": {"id": user_id, "email": email}}, cookie=cookie)

    def handle_login(self) -> None:
        try:
            payload = self.read_json()
        except json.JSONDecodeError:
            self.send_json({"error": "Invalid JSON"}, HTTPStatus.BAD_REQUEST)
            return

        email = str(payload.get("email", "")).strip().lower()
        password = str(payload.get("password", ""))
        with connect() as conn:
            user = conn.execute("SELECT id, email, password_hash FROM users WHERE LOWER(email) = LOWER(%s)", (email,)).fetchone()

        if not user or not verify_password(password, user["password_hash"]):
            self.send_json({"error": "Email or password is incorrect."}, HTTPStatus.UNAUTHORIZED)
            return

        cookie = self.create_session(user["id"])
        self.send_json({"user": {"id": user["id"], "email": user["email"]}}, cookie=cookie)

    def handle_logout(self) -> None:
        cookie_header = self.headers.get("Cookie", "")
        cookies = SimpleCookie(cookie_header)
        token_cookie = cookies.get(SESSION_COOKIE)
        if token_cookie:
            with connect() as conn:
                conn.execute("DELETE FROM sessions WHERE token = %s", (token_cookie.value,))
        secure = "; Secure" if COOKIE_SECURE else ""
        expired = f"{SESSION_COOKIE}=; HttpOnly; SameSite={COOKIE_SAMESITE}; Path=/; Max-Age=0{secure}"
        self.send_json({"ok": True}, cookie=expired)

    def handle_get_data(self) -> None:
        user = self.current_user()
        if not user:
            self.send_json({"error": "Login required"}, HTTPStatus.UNAUTHORIZED)
            return

        with connect() as conn:
            row = conn.execute("SELECT data FROM user_data WHERE user_id = %s", (user["id"],)).fetchone()
        self.send_json({"data": row["data"] if row else None})

    def handle_put_data(self) -> None:
        user = self.current_user()
        if not user:
            self.send_json({"error": "Login required"}, HTTPStatus.UNAUTHORIZED)
            return

        try:
            payload = self.read_json()
        except json.JSONDecodeError:
            self.send_json({"error": "Invalid JSON"}, HTTPStatus.BAD_REQUEST)
            return

        data = payload.get("data")
        if not isinstance(data, dict):
            self.send_json({"error": "Data must be an object."}, HTTPStatus.BAD_REQUEST)
            return

        with connect() as conn:
            conn.execute(
                """
                INSERT INTO user_data (user_id, data, updated_at)
                VALUES (%s, %s, CURRENT_TIMESTAMP)
                ON CONFLICT(user_id) DO UPDATE SET
                  data = excluded.data,
                  updated_at = CURRENT_TIMESTAMP
                """,
                (user["id"], Jsonb(data)),
            )
        self.send_json({"ok": True})


if __name__ == "__main__":
    init_db()
    host = os.environ.get("HOST", "127.0.0.1")
    port = int(os.environ.get("PORT", "8000"))
    server = ThreadingHTTPServer((host, port), BudgetHandler)
    print(f"Budget Studio running at http://{host}:{port}")
    server.serve_forever()
