const crypto = require("crypto");
const { neon } = require("@neondatabase/serverless");

const SESSION_COOKIE = "budget_session";
const PBKDF2_ROUNDS = 200000;

let sql;
let dbReadyPromise;

function getSql() {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is required. Add a Vercel Postgres/Neon database to this project.");
  }

  if (!sql) {
    sql = neon(process.env.DATABASE_URL);
  }

  return sql;
}

async function ensureDb() {
  if (!dbReadyPromise) {
    const db = getSql();
    dbReadyPromise = (async () => {
      await db`
        CREATE TABLE IF NOT EXISTS users (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
      `;
      await db`
        CREATE TABLE IF NOT EXISTS sessions (
          token TEXT PRIMARY KEY,
          user_id INTEGER NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
      `;
      await db`
        CREATE TABLE IF NOT EXISTS user_data (
          user_id INTEGER PRIMARY KEY,
          data JSONB NOT NULL,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
      `;
      await db`CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_idx ON users (LOWER(email))`;
    })();
  }

  await dbReadyPromise;
}

function sendJson(res, statusCode, payload, extraHeaders = {}) {
  res.statusCode = statusCode;
  res.setHeader("Content-Type", "application/json");
  res.setHeader("X-Content-Type-Options", "nosniff");
  Object.entries(extraHeaders).forEach(([key, value]) => res.setHeader(key, value));
  res.end(JSON.stringify(payload));
}

function methodNotAllowed(res, methods) {
  sendJson(res, 405, { error: "Method not allowed" }, { Allow: methods.join(", ") });
}

function getBody(req) {
  if (!req.body) {
    return {};
  }

  if (typeof req.body === "string") {
    return JSON.parse(req.body);
  }

  return req.body;
}

function hashPassword(password) {
  const salt = crypto.randomBytes(16);
  const digest = crypto.pbkdf2Sync(password, salt, PBKDF2_ROUNDS, 32, "sha256");
  return `${PBKDF2_ROUNDS}$${salt.toString("base64")}$${digest.toString("base64")}`;
}

function verifyPassword(password, storedHash) {
  const parts = String(storedHash || "").split("$");
  if (parts.length !== 3) {
    return false;
  }

  const rounds = Number(parts[0]);
  const salt = Buffer.from(parts[1], "base64");
  const expected = Buffer.from(parts[2], "base64");
  const actual = crypto.pbkdf2Sync(password, salt, rounds, expected.length, "sha256");
  return crypto.timingSafeEqual(actual, expected);
}

function parseCookies(req) {
  return Object.fromEntries(
    String(req.headers.cookie || "")
      .split(";")
      .map((cookie) => cookie.trim())
      .filter(Boolean)
      .map((cookie) => {
        const index = cookie.indexOf("=");
        return [cookie.slice(0, index), decodeURIComponent(cookie.slice(index + 1))];
      })
  );
}

function cookieOptions(maxAge) {
  const secure = process.env.VERCEL ? "; Secure" : "";
  const expires = typeof maxAge === "number" ? `; Max-Age=${maxAge}` : "";
  return `HttpOnly; SameSite=Lax; Path=/${expires}${secure}`;
}

function makeSessionCookie(token) {
  return `${SESSION_COOKIE}=${encodeURIComponent(token)}; ${cookieOptions()}`;
}

function clearSessionCookie() {
  return `${SESSION_COOKIE}=; ${cookieOptions(0)}`;
}

async function createSession(userId) {
  const db = getSql();
  const token = crypto.randomBytes(32).toString("base64url");
  await db`INSERT INTO sessions (token, user_id) VALUES (${token}, ${userId})`;
  return token;
}

async function currentUser(req) {
  const cookies = parseCookies(req);
  const token = cookies[SESSION_COOKIE];
  if (!token) {
    return null;
  }

  const db = getSql();
  const rows = await db`
    SELECT users.id, users.email
    FROM sessions
    JOIN users ON users.id = sessions.user_id
    WHERE sessions.token = ${token}
    LIMIT 1
  `;
  return rows[0] || null;
}

module.exports = {
  clearSessionCookie,
  createSession,
  currentUser,
  ensureDb,
  getBody,
  getSql,
  hashPassword,
  makeSessionCookie,
  methodNotAllowed,
  sendJson,
  verifyPassword
};
